# Generated by Django 3.2.9 on 2022-02-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='Ad/')),
                ('title', models.CharField(max_length=40)),
                ('text', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=15)),
                ('comments', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RecentGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='RecentGame/')),
                ('title', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=300)),
                ('comments', models.IntegerField()),
                ('category', models.CharField(max_length=15)),
            ],
        ),
    ]
