# Generated by Django 3.2.9 on 2022-02-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ad_recentgame'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('musobaqa', models.CharField(max_length=50)),
                ('end', models.CharField(max_length=50)),
                ('teams', models.CharField(max_length=50)),
                ('prize', models.CharField(max_length=150)),
            ],
        ),
    ]
