# Generated by Django 3.2.9 on 2022-02-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_gameinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameinfo',
            name='prize',
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='prize1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='prize2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='prize3',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
