# Generated by Django 3.2.9 on 2022-02-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220204_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfo',
            name='img',
            field=models.ImageField(default=1, upload_to='gameinfo/'),
            preserve_default=False,
        ),
    ]
