# Generated by Django 3.2.9 on 2022-02-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_recent'),
    ]

    operations = [
        migrations.AddField(
            model_name='recent',
            name='score',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
